social_networking/config/routes.rb
SocialNetworking::Application.routes.draw do
  devise_for :users
  post 'sinin/validate_user'
  get 'home/welcome'
  get 'home/search_friend'
  post 'home/search_friend'
  resources :posts
  resources :friends

   root 'home#welcome'

  

end

social_networking/app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

social_networking/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

social_networking/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :friends
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

social_networking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

social_networking/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def create_friend
    @message= "Under development section."
  end
end

social_networking/app/controllers/home_controller.rb
class  HomeController < ApplicationController
  before_filter :check_user
  def welcome
    @article = Post.new
    @post =User.find_by_id(current_user.id).posts
  end

  def search_friend
    @friends =User.all
  end

  def check_user
    if current_user.nil?
      redirect_to  new_user_session_path
    end
  end
end

social_networking/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post= current_user.posts.build(post_params)

    if @post.save
      redirect_to home_welcome_path
    else
      @message="Error in your post."
    end
  end

  def post_params
    params.require(:post).permit(:description)
  end
end

social_networking/app/controllers/sinin_controller.rb
class SininController < ApplicationController
  before_filter :authenticate_member!
  def validate_user
    member_signed_in? ? redirect_to home_controller : @message= "Wrong credentials.Try Again"
  end
end

social_networking/app/helpers/application_helper.rb
module ApplicationHelper
end

social_networking/app/views/friends/create.html.erb
<div>
  <h4 class="text-center"><%=@message %></h4>
</div>

social_networking/app/views/home/search_friend.html.erb
<div class="marTop80">
  <% @friends.each do |p|%>
      <%= form_tag friends_path ,method: 'post', html: {class: "form-inline"} do  %>
          <div class="text-left">
            <% if p.email==current_user.email %>
            <% else %>
                <%=p.email %>
                <%= submit_tag "send"  %>
            <% end %>
      <% end %>
  <% end %>

  </div>
</div>

social_networking/app/views/home/welcome.html.erb
<%= form_for @article, html: {class: "form-horizontal"} do |f| %>
    <div class="row marTop15">
      <div class="span1">
        <div class="form-horizontal marTop60 ">
          <div class="span2">
            <div class="text-left">
              <h4>Hello <span><%= current_user.email %></span></h4>
            </div>
          </div>
          <div  class="controls">
            <%= f.text_area :description, size: "60x2" %>
            <%= f.submit "post" %>
<% end %>
</div>
</div>

<div class="span6 text-center"><p class="text-center"><h4>Posts</h4></p>
  <% @post.each do |p| %>
      <%=p.description %><br/>
  <% end %>
</div>
<div class="text-left">
  <%= link_to "search_friend", home_search_friend_path, :method=>:search_friend %>
</div>
</div>
</div>

social_networking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SocialNetworking" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SocialNetworking</a>
          <div class="container nav-collapse pull-right">
            <ul class="nav">
              <!--<li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li> -->

              <% if user_signed_in? %>
                  <%= link_to "logout" , destroy_user_session_path,method: "delete"%>
              <% else %>
                  <%=link_to "login" ,new_user_session_path %>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container ">

          <%= bootstrap_flash %>
          <%= yield %>
    </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

social_networking/app/views/posts/create.html.erb
<div>
<p class="text-error"><%=@message %></p>
</div>

social_networking/app/views/sinin/validate_user.html.erb
<h4 class="text-center"><%= @message %></h4>